# frozen_string_literal: true

# see https://www.vagrantup.com/docs/vagrantfile/version
VAGRANTFILE_API_VERSION = '2'

# see https://www.vagrantup.com/docs/vagrantfile/vagrant_version
Vagrant.require_version '>= 2.2.15'

OUTPUT_VM_BOX     = '{{.BoxName}}'
OUTPUT_VM_BOX_URL = 'file://package.box'

# see https://www.vagrantup.com/docs/vagrantfile/ssh_settings
SSH_FORWARD_AGENT = true
SSH_INSERT_KEY    = false

# see https://www.vagrantup.com/docs/vagrantfile/machine_settings
VM_COMMUNICATOR           = 'ssh'
VM_HOSTNAME               = 'hashicorp'
VM_POST_UP_MESSAGE        = 'Provision, Secure, Connect, Run.'
VM_SYNCED_FOLDER_DISABLED = true
VM_SYNCED_FOLDER_PATH     = '/vagrant'

# see https://www.vagrantup.com/docs/networking/public_network#dhcp
VM_NETWORK_AUTO_CONFIG = true
VM_NETWORK_HOSTNAME    = true
VM_NETWORK_IP          = '10.47.42.77'

# see https://www.vagrantup.com/docs/providers/virtualbox/configuration
VIRTUALBOX_CHECK_GUEST_ADDITIONS = false
VIRTUALBOX_GUI                   = false
VIRTUALBOX_NAME                  = VM_HOSTNAME
VIRTUALBOX_CPU                   = 2
VIRTUALBOX_MEMORY                = 4096

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "source", autostart: false do |source|
    source.vm.box = "{{.SourceBox}}"
  	config.ssh.insert_key = {{.InsertKey}}
  end

  config.vm.define "{{.BoxName}}" do |output|
    output.vm.box = "{{.BoxName}}"
    output.vm.box_url = "file://package.box"
    config.ssh.insert_key = false
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
end
