Vagrant.configure("2") do |config|
  config.vm.define "source", autostart: false do |source|
    source.vm.box = "{{.SourceBox}}"
  	config.ssh.insert_key = {{.InsertKey}}
  end

  config.vm.define "{{.BoxName}}" do |output|
    output.vm.box = "{{.BoxName}}"
    output.vm.box_url = "file://package.box"
    config.ssh.insert_key = false
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
end
